server:
    port: 8000

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://JWT-AUTH
              predicates:
                - Path=/shop/authent/**


jwt:
  secret: "Hi#This1!$-My!Secret_Key@hereWeCanAdd*2AnyThingFor&3JWTAuthentication"